name: Test blog

on:
  push:
  pull_request:

jobs:
  build-test:
    name: Test build using ${{ matrix.bundler }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bundler:
          - webpack
          - vite
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install Deps
        run: pnpm install --no-frozen-lockfile

      - name: Build Blog with ${{ matrix.bundler }}
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build:${{ matrix.bundler }}

  linter-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install Deps
        run: pnpm install --no-frozen-lockfile

      - name: Linter test
        run: pnpm run lint
